/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generatejavabean.ui;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

import generatejavabean.configbeans.ConnectionData;
import generatejavabean.popup.actions.GenerateJavaBeanAction;
import generatejavabean.tools.ConfigTools;
import generatejavabean.tools.DatabaseConnTool;
import generatejavabean.tools.DatabaseQueryTool;

/**
 *
 * @author Administrator
 */
@SuppressWarnings("serial")
public class DbConnPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDemo
     */
    public DbConnPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        txtSchemaName = new javax.swing.JTextField();
        txtUrl = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnTest = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        labelConfigName = new javax.swing.JLabel();
        radioOracle = new javax.swing.JRadioButton();
        radioMySql = new javax.swing.JRadioButton();
        labelDataType = new javax.swing.JLabel();
        labelUrl = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelPwd = new javax.swing.JLabel();
        labelSchemaName = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        tip = new javax.swing.JLabel();

        // 加入buttonGroup后一次只能选择一个
        dbTypeBtngroup = new ButtonGroup();
        dbTypeBtngroup.add(radioMySql);
        dbTypeBtngroup.add(radioOracle);
        // 读取文件获取保存数据库连接的信息，再初始化显示信息
        connData = ConfigTools.getDbConfig();
        tip.setForeground(new java.awt.Color(255, 0, 0));

        final Pattern p = Pattern.compile("[A-Za-z0-9_]");
        txtUserName.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                Matcher m = p.matcher(e.getKeyChar() + "");
                if (m.matches()) {
                    String txt = txtSchemaName.getText() == null ? "" : txtSchemaName.getText();
                    txt = txt + e.getKeyChar();
                    txtSchemaName.setText(txt.toUpperCase());
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                // TODO Auto-generated method stub

            }

            @Override
            public void keyPressed(KeyEvent e) {

            }
        });

        btnTest.setText("test connect");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnNext.setText("next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        labelConfigName.setText("DataBase Configeration");

        radioOracle.setText(ConfigTools.DB_TYPE_ORCL);
        radioOracle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOracleActionPerformed(evt);
            }
        });

        radioMySql.setText(ConfigTools.DB_TYPE_MYSQL);
        radioMySql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMySqlActionPerformed(evt);
            }
        });

        labelDataType.setText("DataBase Type:");

        labelUrl.setText("Connect URL:");

        labelUserName.setText("User Name:");

        labelPwd.setText("Password:");

        labelSchemaName.setText("Schema Name:");

        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap(128, Short.MAX_VALUE).addGroup(layout
                                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                                                                        layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(labelDataType).addComponent(labelUrl).addComponent(labelUserName).addComponent(labelPwd).addComponent(labelSchemaName)).addGap(18, 18, 18)
                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(txtPwd, javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtSchemaName, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                        .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtUrl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                        layout.createSequentialGroup().addGap(22, 22, 22)
                                                                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(btnTest)
                                                                                                                                                                        .addGroup(layout.createSequentialGroup().addGap(20, 20, 20).addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(tip))))))
                        .addGroup(layout.createSequentialGroup().addGap(135, 135, 135).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(labelConfigName).addGroup(layout.createSequentialGroup().addComponent(radioOracle).addGap(36, 36, 36).addComponent(radioMySql))))).addContainerGap(178, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addContainerGap(24, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(labelDataType).addGap(15, 15, 15)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup().addComponent(labelConfigName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(radioOracle).addComponent(radioMySql))
                                                                        .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(labelUrl).addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(labelUserName).addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(labelSchemaName).addComponent(txtSchemaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(labelPwd).addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addComponent(btnTest).addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnNext).addComponent(tip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap(66, Short.MAX_VALUE)));
        // 初始化面板数据
        this.initPanelDbConnInfo(connData);
    }// </editor-fold>

    /**
     * 初始化面板数据
     * 
     * @param data
     */
    private void initPanelDbConnInfo(ConnectionData data) {
        // 数据库连接类型
        if (radioMySql.getText().equals(data.getDbType())) {
            radioMySql.setSelected(true);
        } else {
            radioOracle.setSelected(true);
        }
        // 连接url
        txtUrl.setText(data.getUrl());
        // 连接用户名
        txtUserName.setText(data.getUserName());
        // schema name
        txtSchemaName.setText(data.getSchemaName());
        // password
        txtPwd.setText(data.getPwd());
    }

    // 测试连接数据库是否成功
    private boolean btnTestActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.getAndSaveConnectionData();
            DatabaseConnTool.getConnection(connData);
            JOptionPane.showMessageDialog(this.getRootPane(), "连接成功。");
            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this.getRootPane(), "连接失败。\n" + e.toString());
        }
        return false;
    }

    public boolean isConnection() {
        try {
            this.getAndSaveConnectionData();
            DatabaseConnTool.getConnection(connData);
            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this.getRootPane(), "连接失败。\n" + e.toString());
        }
        return false;
    }

    // 点击下一步
    public void btnNextActionPerformed(java.awt.event.ActionEvent evt) {
        this.getAndSaveConnectionData();
        SelectTablePanel.tablesList.setModel(new javax.swing.AbstractListModel<String>() {
            // 查询指定表空间下的所有表的名称，并在列表显示
            List<String> tableItemsList = DatabaseQueryTool.getTablesList(connData);

            public int getSize() {
                return tableItemsList.size();
            }

            public String getElementAt(int i) {
                return tableItemsList.get(i);
            }
        });
        SelectTablePanel.connData = connData;
        CardLayout cardLayout = (CardLayout) this.getParent().getLayout();
        cardLayout.show(this.getParent(), GenerateJavaBeanAction.TABLE_PANEL_NAME);
    }

    /**
     * 校验对话框中的信息并保存
     */
    private void getAndSaveConnectionData() {
        // 连接类型
        String dbType = radioMySql.isSelected() ? radioMySql.getText() : radioOracle.getText();
        connData.setDbType(dbType);
        // url
        String url = txtUrl.getText();
        if (url == null || "".equals(url.trim())) {
            tip.setText("url must not be null.");
            return;
        }
        connData.setUrl(url);
        // userName
        String userName = txtUserName.getText();
        if (userName == null || "".equals(userName.trim())) {
            tip.setText("userName must not be null.");
            return;
        }
        connData.setUserName(userName);
        // schema
        String schemaName = txtSchemaName.getText();
        if (schemaName == null || "".equals(schemaName.trim())) {
            tip.setText("schemaName must not be null.");
            return;
        }
        connData.setSchemaName(schemaName);
        // password
        String password = txtPwd.getText();
        if (password == null || "".equals(password.trim())) {
            tip.setText("password must not be null.");
            return;
        }
        connData.setPwd(password);
        // 消除错误提示
        tip.setText("");
        // 保存配置信息
        ConfigTools.saveDbConfig(connData);
    }

    private void radioOracleActionPerformed(java.awt.event.ActionEvent evt) {
        // none
    }

    private void radioMySqlActionPerformed(java.awt.event.ActionEvent evt) {
        // none
    }

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public ConnectionData getConnData() {
        return connData;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton        btnNext;
    private javax.swing.JButton        btnTest;
    private javax.swing.JLabel         labelConfigName;
    private javax.swing.JLabel         labelDataType;
    private javax.swing.JLabel         labelPwd;
    private javax.swing.JLabel         labelSchemaName;
    private javax.swing.JLabel         labelUrl;
    private javax.swing.JLabel         labelUserName;
    private javax.swing.JRadioButton   radioMySql;
    private javax.swing.JRadioButton   radioOracle;
    private ButtonGroup                dbTypeBtngroup;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField     txtSchemaName;
    private javax.swing.JTextField     txtUrl;
    private javax.swing.JTextField     txtUserName;
    private javax.swing.JLabel         tip;
    // End of variables declaration
    private ConnectionData             connData;

}
