/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generatejavabean.ui;

import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;

import org.apache.velocity.VelocityContext;
import org.apache.velocity.app.VelocityEngine;

import generatejavabean.popup.actions.GenerateJavaBeanAction;
import generatejavabean.tools.ConfigTools;
import generatejavabean.tools.TemplateTool;

/**
 *
 * @author Administrator
 */
@SuppressWarnings("serial")
public class SelectTablePanel extends javax.swing.JPanel {

	/**
	 * Creates new form JPanelSelected
	 */
	public SelectTablePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		labelSelected = new javax.swing.JLabel();
		radioJavaBean = new javax.swing.JRadioButton();
		radioRepository = new javax.swing.JRadioButton();
		radioService = new javax.swing.JRadioButton();
		btnPrevious = new javax.swing.JButton();
		panelTables = new javax.swing.JScrollPane();
		tablesList = new javax.swing.JList<>();
		btnFinish = new javax.swing.JButton();
		labelTables = new javax.swing.JLabel();
		btnClose2 = new javax.swing.JButton();
		cboxNewFolder = new javax.swing.JCheckBox();
		txtNewFolderName = new javax.swing.JTextField();
		panelSelected = new javax.swing.JScrollPane();
		selectedList = new javax.swing.JList<>();

		labelSelected.setText("Selected");

		radioJavaBean.setText("create javaBean");
		radioJavaBean.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				radioJavaBeanActionPerformed(evt);
			}
		});

		radioRepository.setText("create repository");
		radioRepository.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				radioRepositoryActionPerformed(evt);
			}
		});

		radioService.setText("create service");
		radioService.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				radioServiceActionPerformed(evt);
			}
		});

		btnPrevious.setText("pervious");
		btnPrevious.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPreviousActionPerformed(evt);
			}
		});
		// 已选的表
		tablesList.addMouseListener(new MouseListener() {
			@Override
			public void mouseReleased(MouseEvent e) {
			}

			@Override
			public void mousePressed(MouseEvent e) {

			}

			@Override
			public void mouseExited(MouseEvent e) {

			}

			@Override
			public void mouseEntered(MouseEvent e) {

			}

			@Override
			public void mouseClicked(MouseEvent e) {
				// e.getButton()：1 左键 3 右键
				List<String> selectedValuesList = tablesList.getSelectedValuesList();
				ListModel<String> selectedItems = selectedList.getModel();
				for (int i = 0; i < selectedItems.getSize(); i++) {
					if (!selectedValuesList.contains(selectedItems.getElementAt(i))) {
						selectedValuesList.add(selectedItems.getElementAt(i));
					}
				}
				selectedList.setModel(new javax.swing.AbstractListModel<String>() {
					public int getSize() {
						return selectedValuesList.size();
					}

					public String getElementAt(int i) {
						return selectedValuesList.get(i);
					}
				});
			}
		});
		selectedList.addMouseListener(new MouseListener() {
			@Override
			public void mouseReleased(MouseEvent e) {

			}

			@Override
			public void mousePressed(MouseEvent e) {

			}

			@Override
			public void mouseExited(MouseEvent e) {

			}

			@Override
			public void mouseEntered(MouseEvent e) {

			}

			@Override
			public void mouseClicked(MouseEvent e) {
				String selectedValue = selectedList.getSelectedValue();
				if (selectedValue != null) {
					ListModel<String> selectedItems = selectedList.getModel();
					List<String> selectedValuesList = new ArrayList<>();
					for (int i = 0; i < selectedItems.getSize(); i++) {
						if (!selectedValue.equals(selectedItems.getElementAt(i))) {
							selectedValuesList.add(selectedItems.getElementAt(i));
						}
					}
					selectedList.setModel(new javax.swing.AbstractListModel<String>() {
						public int getSize() {
							return selectedValuesList.size();
						}

						public String getElementAt(int i) {
							return selectedValuesList.get(i);
						}
					});
				}
			}
		});
		panelTables.setViewportView(tablesList);
		selectedList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		panelSelected.setViewportView(selectedList);

		btnFinish.setText("finish");
		btnFinish.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnFinishActionPerformed(evt);
			}
		});

		labelTables.setText("Tables");

		btnClose2.setText("close");
		btnClose2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnClose2ActionPerformed(evt);
			}
		});

		cboxNewFolder.setText("creat new folder");
		cboxNewFolder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cboxNewFolderActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addComponent(panelTables, javax.swing.GroupLayout.PREFERRED_SIZE, 189,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(162, 162, 162)
														.addComponent(labelSelected))
										.addGroup(layout.createSequentialGroup().addGap(48, 48, 48).addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addComponent(btnPrevious)
														.addGap(32, 32, 32).addComponent(btnFinish)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(btnClose2))
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(cboxNewFolder).addGap(18, 18, 18)
																.addComponent(txtNewFolderName,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 83,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(radioJavaBean)
														.addComponent(panelSelected,
																javax.swing.GroupLayout.PREFERRED_SIZE, 258,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(radioRepository).addComponent(radioService))
														.addGap(0, 68, Short.MAX_VALUE)))))
										.addGap(23, 23, 23))
								.addGroup(layout.createSequentialGroup().addGap(76, 76, 76).addComponent(labelTables)))
						.addGap(28, 28, 28)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(labelTables).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup()
										.addComponent(panelTables, javax.swing.GroupLayout.PREFERRED_SIZE, 405,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
								.addGroup(layout.createSequentialGroup().addComponent(labelSelected)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(panelSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 103,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(34, 34, 34).addComponent(radioJavaBean).addGap(18, 18, 18)
										.addComponent(radioRepository).addGap(18, 18, 18).addComponent(radioService)
										.addGap(29, 29, 29)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(cboxNewFolder).addComponent(txtNewFolderName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnPrevious).addComponent(btnFinish)
												.addComponent(btnClose2))
										.addGap(41, 41, 41)))));
	}// </editor-fold>

	private void radioJavaBeanActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void radioRepositoryActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void radioServiceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * 返回上一个panel
	 * 
	 * @param evt
	 */
	private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {
		CardLayout cardLayout = (CardLayout) this.getParent().getLayout();
		cardLayout.show(this.getParent(), GenerateJavaBeanAction.DB_PANEL_NAME);
	}

	// 确定生成文件按钮
	// F:\workspaces\sts\multiJavaPrj\src\dbToJavaBean
	private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {
		String path = ConfigTools.getFolderPath();
		System.out.println(path);
		VelocityEngine engine = TemplateTool.getVelocityEngine();
		System.out.println(engine.toString());
		ListModel<String> selectedTables = selectedList.getModel();
		for (int i = 0; i < selectedTables.getSize(); i++) {
			VelocityContext context = new VelocityContext();
			String tableName = selectedTables.getElementAt(i);
			StringWriter writer = new StringWriter();
			engine.mergeTemplate(TemplateTool.TEMPLATE_PATH_BEAN, TemplateTool.ENCODING, context, writer);
			System.out.println(writer.toString());
			// 包路径
			// context.put("package", );
			// // 表空间名
			// context.put("schemaName", schemaName);
			// // 格式化的表名
			// String tabNameFmt =
			// StringUtil.toJavaBeanNameAndUpperFirstChar(tableName);
			// context.put("tabNameFmt", tabNameFmt);
			// String primaryColName =
			// DatabaseTools.getPrimaryColumnName(tableName);
			// // 当前时间
			// context.put("curDate", DateUtil.DATE_FORMAT3.format(new Date()));
			// // 主键名
			// context.put("primaryColName", primaryColName);
			// // 除了主键的列信息
			// List<ColumnDetail> columnList =
			// DatabaseTools.getColumnDetailMap(tableName, primaryColName);
			// context.put("columnList", columnList);
			// // 生成的Java文件路径
			// String filePath = templateTools.getJavaBeanFileRootPath() +
			// File.separatorChar + tabNameFmt + ".java";
			// writer = new BufferedWriter(
			// new OutputStreamWriter(new FileOutputStream(filePath),
			// templateTools.getEncode()));
			// template.merge(context, writer);
			// writer.flush();
		}
	}

	/**
	 * 隐藏窗口，并返回第一个panel
	 * 
	 * @param evt
	 */
	private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {
		JFrame jf = (JFrame) this.getRootPane().getParent();
		jf.setVisible(false);
	}

	private void cboxNewFolderActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnClose2;
	private javax.swing.JButton btnFinish;
	private javax.swing.JButton btnPrevious;
	private javax.swing.JCheckBox cboxNewFolder;
	private javax.swing.JLabel labelSelected;
	private javax.swing.JLabel labelTables;
	private javax.swing.JScrollPane panelSelected;
	private javax.swing.JScrollPane panelTables;
	private javax.swing.JRadioButton radioJavaBean;
	private javax.swing.JRadioButton radioRepository;
	private javax.swing.JRadioButton radioService;
	private javax.swing.JList<String> selectedList;
	private javax.swing.JTextField txtNewFolderName;
	// End of variables declaration
	public static javax.swing.JList<String> tablesList;
}
